// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPklQi6LZIILmaRj0Ffz52MGCKuOOUuig',
    appId: '1:167981569123:web:b7ac1b6f5ad3623545d456',
    messagingSenderId: '167981569123',
    projectId: 'flutterfireprojek',
    authDomain: 'flutterfireprojek.firebaseapp.com',
    storageBucket: 'flutterfireprojek.appspot.com',
    measurementId: 'G-B6T31TTH7T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMqv-LtCpAtfG-b4HrBawX_ZLH0Efdmss',
    appId: '1:167981569123:android:97392f85f56bc98845d456',
    messagingSenderId: '167981569123',
    projectId: 'flutterfireprojek',
    storageBucket: 'flutterfireprojek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABZRL7iU7zPqa1t1G52bncS_FcA5ifFIc',
    appId: '1:167981569123:ios:341b80a15289f6c345d456',
    messagingSenderId: '167981569123',
    projectId: 'flutterfireprojek',
    storageBucket: 'flutterfireprojek.appspot.com',
    iosBundleId: 'com.example.tugasKelompok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABZRL7iU7zPqa1t1G52bncS_FcA5ifFIc',
    appId: '1:167981569123:ios:341b80a15289f6c345d456',
    messagingSenderId: '167981569123',
    projectId: 'flutterfireprojek',
    storageBucket: 'flutterfireprojek.appspot.com',
    iosBundleId: 'com.example.tugasKelompok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPklQi6LZIILmaRj0Ffz52MGCKuOOUuig',
    appId: '1:167981569123:web:2056c8de56a4e69645d456',
    messagingSenderId: '167981569123',
    projectId: 'flutterfireprojek',
    authDomain: 'flutterfireprojek.firebaseapp.com',
    storageBucket: 'flutterfireprojek.appspot.com',
    measurementId: 'G-ETK1MXLV8B',
  );
}
